Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      EmailVerificationSubject: "MtG League Manager: Verify Account"
      EmailVerificationMessage: "Please use the following code to verify your account: {####}."
      SmsVerificationMessage: "Please use the following code to verify your account: {####}."
      UserPoolName: ${opt:stage}-mtglm-user-pool
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        -   
          AttributeDataType: "Number"
          Mutable: true
          Name: "firstTimeLogin"
          NumberAttributeConstraints: 
            MinValue: 0
            MaxValue: 1
        -   
          AttributeDataType: "String"
          Mutable: true
          Name: "role"
              

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${opt:stage}-mtglm-user-pool-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

Outputs:
  UserPoolName:
    Value: ${opt:stage}-mtglm-user-pool
    Export:
      Name: ${self:provider.stage}-mtglm-UserPoolName

  UserPoolArn:
    Value:
      Fn::Join:
        - "" 
        - - "arn:aws:cognito-idp:${self:provider.region}:"
          - Ref: "AWS::AccountId"
          - ":userpool/"
          - Ref: "CognitoUserPool"
    Export:
      Name: ${self:provider.stage}-mtglm-UserPoolArn

  UserPoolId:
    Value:
      Ref: CognitoUserPool
    Export:
      Name: ${self:provider.stage}-mtglm-UserPoolId

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
    Export:
      Name: ${self:provider.stage}-mtglm-UserPoolClientId
