service: mtglm-auth

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  memorySize: 128
  environment:
    USER_POOL_ID: ${env:USER_POOL_ID}
    CLIENT_ID: ${env:CLIENT_ID}
    ALLOWED_ORIGIN: ${env:ALLOWED_ORIGIN}

package:
  include:
    - ../build/**
    - ../node_modules/**

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-aws-documentation

custom:
  documentation: ${file(partials/documentation.yml)}

resources:
  - ${file(partials/cognito.yml)}
  

functions:
  ConfirmRegistration: ${file(partials/functions/confirm_registration.yml)}
  Login: ${file(partials/functions/login.yml)}
  Logout: ${file(partials/functions/logout.yml)}
  ResendCode: ${file(partials/functions/resend_code.yml)}
  SignUp: ${file(partials/functions/sign_up.yml)}
  Validate: ${file(partials/functions/validate.yml)}
